name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'  # Trigger workflow on any tag push
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract Git Tag
      - name: Extract Git Tag
        id: extract_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "TAG=$TAG"
          echo "tag=$TAG" >> $GITHUB_ENV

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Build and push the Docker image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            muhohoweb/course-image:latest  # Optionally keep a "latest" tag